### ISSUE TITLE
Esquecemos de excluir `extract_cities_api`?

### ISSUE THREAD

**Issue by cuducos** [FelipeSBarros/crossfire#20]
https://github.com/FelipeSBarros/crossfire/blob/36e8a43808b92d9c7321b8060a7413c44845cf58/Python/crossfire/crossfire/fogocruzado_utils.py#L33

Isso teria que ser excluído no #18, não?

**Comment by FelipeSBarros** [comment]
um... acho que não.
Esse [endpoint](https://api.fogocruzado.org.br/docs/endpoint/cities) ainda existe.
Estava vendo agora que teremos que reescrever. Vou colocar isso na issue.
O que removemos foi uma função que apenas retornada uma coluna em fomrato floating...

**Comment by cuducos** [comment]
Ah, perfeito então!

**Comment by FelipeSBarros** [comment]
> Ah, perfeito então!

Ufa. Suei frio aqui...
rs
