### ISSUE TITLE
Remover diretorio `dist/`

### ISSUE THREAD

**Issue by cuducos** [FelipeSBarros/crossfire#21]
Esse diretório é gerado automaticamente e não há razão para mantê-lo no repositório… ou estou esquecendo algum detalhe?

**Comment by FelipeSBarros** [comment]
Ok. Devo fazer isso e limpar do histórico, né?

**Comment by cuducos** [comment]
> limpar do histórico

Não, isso quebraria o repositório de qualquer pessoa que tiver clonado. Só removemos, adicionamos o caminho ao `.gitignore` e pronto. Bola para frente.
