### ISSUE TITLE
Parâmetro `max_parallel_requests` de `AsyncClient` não está sendo aproveitado no método `occurrences`

### ISSUE THREAD

**Issue by FelipeSBarros** [FelipeSBarros/crossfire#75]
Na refatoração e conversão da classe `Client` em `AsyncClient` (#74)  [percebemos um bug](https://github.com/FelipeSBarros/crossfire/pull/74#discussion_r1406651714) já que o `max_parallel_requests`passado para a instância da classe não é usada no método `occurrences`.
@cuducos designei a vc, mas só para vc confirmar se está bem o texto. Não quer dizer que vc tenha que resolver isso. Mias à frente eu posso fazer, com a sua supervisão.

**Comment by cuducos** [comment]
Excelente, bem claro. 

E posso ficar responsável por essa sim!

**Comment by FelipeSBarros** [comment]
Como vc pensa em solucionar isso? Criando um atributo que vai receber o parâmetro `max_parallel_requests` e com isso usá-lo em `Occurrences`? 
Existe outra forma melhor?

**Comment by cuducos** [comment]
Espie o #80

**Comment by FelipeSBarros** [comment]
> Espie o #80

Aprovado.
