### ISSUE TITLE
Adicionar `initial_date` e `final_date` ao método `occurrences`

### ISSUE THREAD

**Issue by FelipeSBarros** [FelipeSBarros/crossfire#83]
@cuducos 
O [end point Occurrences](https://api.fogocruzado.org.br/docs/endpoint/occurrences) aceita um parametro de data inicial e data final para a requisição de dados de tiroteio.
As datas devem estar no formato: `2023-07-13`;
Esse parâmetro não está implementado. 
Vou implementar-los mas fiquei com algumas dúvidas:
Seria o caso de validar a ordem da data passada pelo usuário? 
E a forma como ela foi escrita usado `-` e não `/`?

**Comment by FelipeSBarros** [comment]
Fiz uns testes e o end point retorna dados com `initialdate`, com `enddate` e com ambos. Então, entendo que não é necessário estabelecer dependencia entre os parâmetros de `initial_date` e `final_date`.

**Comment by cuducos** [comment]
> Seria o caso de validar a ordem da data passada pelo usuário?
> …
> Então, entendo que não é necessário estabelecer dependencia entre os parâmetros de `initial_date` e `final_date`.

Talvez uma lógica como:

```python
if initial_date and final_date:
    # validate initial < final
````

> E a forma como ela foi escrita usado `-` e não `/`?

Podemos aceitar os dois e formatar nós mesmos. Por exemplo, para entradas como:

* `2023-07-13`
* `2023/07/13`
* `20230713`

Se a gente retirar tudo que não for número, fizer um _parse_ para um objeto `datetime.date` e depois formatar com `Y%-%m-%d` teremos resultados válidos…
