### ISSUE TITLE
`format` Occurrences' parameter not working

### ISSUE THREAD

**Issue by FelipeSBarros** [FelipeSBarros/crossfire#90]
Trying the crossfire package, I could see that the parameter `format` in `Occurrences`  is useless.
Do not return `df`,  `gdf` neigther an error when format doesn't exists:

```python
from crossfire import occurrences
occurrences(id_state='813ca36b-91e3-4a18-b408-60b27a1942ef',
                id_cities='5bd3bfe5-4989-4bc3-a646-fe77a876fce0',
                format='fourty-two')



from crossfire import Client
client = Client()
occ = client.occurrences(id_state='813ca36b-91e3-4a18-b408-60b27a1942ef',
                id_cities='5bd3bfe5-4989-4bc3-a646-fe77a876fce0',
                format='fourty-two')
```
I could see that, in `Occurrences`, the [`client.get`](https://github.com/FelipeSBarros/crossfire/blob/2f15ecfa619e913f9daa665a42733ceab0947fba/crossfire/clients/occurrences.py#L101C46-L101C46), has only `url` as parameter. Shouldn't `format` be passed also?
```python
                occurrences, metadata = await self.client.get(url)

```

On the other hand, in `cities`, it is been used:

```python

from crossfire import cities


cities(state_id='813ca36b-91e3-4a18-b408-60b27a1942ef', format='df')
```

@cuducos I can find a way to solve this. Just appreciate your consideration about ir.

**Comment by cuducos** [comment]
Good catch. Add some calls with `format="df"` and `format="geodf"` in `test_occurrences_client.py` and we can crush this bug!
